---
abstract: 'Various portability utilities for module builders'
author:
  - 'Ken Williams <kwilliams@cpan.org>'
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  Cwd: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-Helpers
requires:
  Config: 0
  Exporter: 5.57
  ExtUtils::MakeMaker: 0
  File::Basename: 0
  File::Copy: 0
  File::Spec::Functions: 0
  Pod::Man: 0
  Text::ParseWords: 3.24
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=ExtUtils-Helpers
  repository: git://github.com/Leont/extutils-helpers.git
version: 0.011
